name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=ancrard_Laboratorio-Calidad-Sistemas2
            -Dsonar.organization=ancrard
            -Dsonar.sources=.
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
